"""HTML reports for the dedup workflow.

Three self-contained HTML documents, all generated by ``find_duplicate_photos
report``:

  ``render_html_report``           — side-by-side duplicate review (thumbnails
                                     + tier badges) for manual delete-in-Explorer.
  ``render_singletons_html_report``— files that didn't cluster with anything,
                                     grouped by year. Catches misses.
  ``render_stats_html_report``     — library overview: totals, by-year /
                                     by-extension / by-media-kind tables, and
                                     a duplicate-bytes-reclaimable summary.

Thumbnails are inlined as base64 so each file is portable.
"""
from __future__ import annotations

import base64
import html
import io
import logging
import os
from typing import Iterable

from PIL import Image

from photo_lib.config import BUNDLED_EARLY_FOLDER, BUNDLED_EARLY_YEAR_RANGE
from photo_lib.duplicate_finder import DuplicateGroup, FileFingerprint
from photo_lib.filename_pattern import CANONICAL_FILENAME_PARTS_RE

_BUNDLED_EARLY_YEARS = set(range(*BUNDLED_EARLY_YEAR_RANGE))

logger = logging.getLogger("photo_lib")

THUMBNAIL_MAX_PX = 240
TIER_LABELS = {
    1: ("Tier 1", "byte-identical file", "#1f7a1f"),
    2: ("Tier 2", "identical pixels", "#1f5a7a"),
    3: ("Tier 3", "perceptually identical", "#7a3f1f"),
}


def _thumbnail_data_uri(path: str, max_px: int = THUMBNAIL_MAX_PX) -> str | None:
    try:
        with Image.open(path) as image:
            image = image.convert("RGB")
            image.thumbnail((max_px, max_px))
            buffer = io.BytesIO()
            image.save(buffer, format="JPEG", quality=78)
            encoded = base64.b64encode(buffer.getvalue()).decode("ascii")
            return f"data:image/jpeg;base64,{encoded}"
    except Exception as exc:
        logger.debug("Thumbnail failed for %s: %s", path, exc)
        return None


def precompute_thumbnails(
    paths: list[str],
    max_workers: int = 8,
    log_every: int = 1000,
) -> dict[str, str | None]:
    """Generate thumbnail data URIs for ``paths`` in parallel.

    On an external HDD the sequential thumbnail loop was the report's
    bottleneck — ~150-300ms per file × 30k = 1.5 hours wall-clock with
    no progress visibility. PIL's image decode releases the GIL, so a
    small thread pool cuts wall-clock by 5-8× and we can emit ticks so
    the operator knows roughly where it is.
    """
    from concurrent.futures import ThreadPoolExecutor, as_completed
    total = len(paths)
    if total == 0:
        return {}
    logger.info("Generating %d thumbnails (%d workers in parallel)...",
                total, max_workers)
    out: dict[str, str | None] = {}
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        future_to_path = {
            executor.submit(_thumbnail_data_uri, p): p for p in paths
        }
        for index, future in enumerate(as_completed(future_to_path), start=1):
            path = future_to_path[future]
            try:
                out[path] = future.result()
            except Exception as exc:
                logger.debug("Thumbnail failed for %s: %s", path, exc)
                out[path] = None
            if index % log_every == 0:
                logger.info("  thumbnails: %d / %d", index, total)
    logger.info("  thumbnails: %d / %d (done)", total, total)
    return out


def _format_size(byte_count: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if byte_count < 1024:
            return f"{byte_count:.1f} {unit}" if unit != "B" else f"{byte_count} B"
        byte_count /= 1024
    return f"{byte_count:.1f} TB"


def _source_label_for(
    fingerprint: FileFingerprint,
    source_labels: dict[str, str] | None,
) -> str | None:
    if not source_labels:
        return None
    return source_labels.get(os.path.normpath(fingerprint.path))


def _render_card(
    fingerprint: FileFingerprint,
    position: int,
    library_root: str,
    source_labels: dict[str, str] | None = None,
    thumbnails: dict[str, str | None] | None = None,
) -> str:
    # Prefer the precomputed thumbnail cache if the caller went through
    # precompute_thumbnails(). Falls back to lazy single-threaded
    # generation otherwise (preserves the previous behavior for callers
    # that haven't been updated).
    if thumbnails is not None and fingerprint.path in thumbnails:
        thumbnail = thumbnails[fingerprint.path]
    else:
        thumbnail = _thumbnail_data_uri(fingerprint.path)
    thumb_html = (
        f'<img src="{thumbnail}" />'
        if thumbnail
        else '<div class="no-thumb">no preview</div>'
    )
    relpath = os.path.relpath(fingerprint.path, library_root)
    dimensions = (
        f"{fingerprint.width}×{fingerprint.height}"
        if fingerprint.width and fingerprint.height
        else "?"
    )
    is_winner = position == 0
    badge = '<span class="winner">winner</span>' if is_winner else ""
    source_label = _source_label_for(fingerprint, source_labels)
    source_html = (
        f'<span class="src-badge" title="source library">'
        f'src: {html.escape(source_label)}</span>'
        if source_label else ""
    )
    return (
        f'<div class="card{" winner-card" if is_winner else ""}">'
        f'  <div class="thumb">{thumb_html}</div>'
        f'  <div class="meta">'
        f'    {badge}{source_html}'
        f'    <div class="path">{html.escape(relpath)}</div>'
        f'    <div class="stats">{dimensions} · {_format_size(fingerprint.size)}</div>'
        f'  </div>'
        f'</div>'
    )


def _is_cross_date_group(group: DuplicateGroup) -> bool:
    """A group spans different timestamps when its canonical members don't all
    share the same ``<base>``. Non-canonical members are ignored (they don't
    contribute a base anyway). A group with 0-1 distinct bases is NOT
    cross-date.
    """
    bases: set[str] = set()
    for fingerprint in group.fingerprints:
        match = CANONICAL_FILENAME_PARTS_RE.match(os.path.basename(fingerprint.path))
        if match:
            bases.add(match.group("base"))
    return len(bases) >= 2


def _render_group(
    group: DuplicateGroup,
    library_root: str,
    source_labels: dict[str, str] | None = None,
    thumbnails: dict[str, str | None] | None = None,
) -> str:
    label, blurb, color = TIER_LABELS[group.tier]
    cards = "\n".join(
        _render_card(fingerprint, position, library_root,
                     source_labels=source_labels, thumbnails=thumbnails)
        for position, fingerprint in enumerate(group.ranked())
    )
    cross_date_badge = (
        '<span class="cross-date-badge" '
        'title="Group members have different timestamps — pick which date is the true one">'
        'cross-date</span>'
        if _is_cross_date_group(group) else ""
    )
    return (
        f'<div class="group">'
        f'  <div class="group-header" style="border-left-color: {color}">'
        f'    <span class="tier-badge" style="background: {color}">{label}</span>'
        f'    <span class="tier-blurb">{blurb}</span>'
        f'    {cross_date_badge}'
        f'    <span class="count">{len(group.fingerprints)} files</span>'
        f'  </div>'
        f'  <div class="cards">{cards}</div>'
        f'</div>'
    )


_HTML_HEAD = """<!doctype html>
<html><head><meta charset="utf-8"><title>Duplicate review</title>
<style>
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
       margin: 1.5rem; background: #f6f6f6; }
h1 { font-size: 1.3rem; }
.summary { background: #fff; padding: 0.75rem 1rem; border-radius: 6px;
           margin-bottom: 1rem; }
.group { background: #fff; border-radius: 6px; margin-bottom: 0.75rem;
         padding: 0.5rem 0.75rem; }
.group-header { border-left: 4px solid; padding-left: 0.6rem; margin-bottom: 0.4rem;
                display: flex; gap: 0.6rem; align-items: center;
                font-size: 0.9rem; }
.tier-badge { color: #fff; padding: 0.1rem 0.5rem; border-radius: 3px;
              font-weight: bold; font-size: 0.8rem; }
.tier-blurb { color: #555; }
.count { margin-left: auto; color: #777; font-size: 0.85rem; }
.cards { display: flex; flex-wrap: wrap; gap: 0.5rem; }
.card { width: 260px; background: #fafafa; border-radius: 4px; padding: 0.4rem;
        border: 1px solid #e6e6e6; }
.card.winner-card { border-color: #1f7a1f; box-shadow: 0 0 0 1px #1f7a1f55; }
.thumb { width: 100%; aspect-ratio: 1 / 1; background: #ddd; border-radius: 3px;
         display: flex; align-items: center; justify-content: center;
         overflow: hidden; }
.thumb img { max-width: 100%; max-height: 100%; }
.no-thumb { color: #888; font-size: 0.8rem; }
.meta { padding-top: 0.4rem; font-size: 0.8rem; }
.path { font-family: ui-monospace, Consolas, monospace; word-break: break-all;
        color: #222; }
.stats { color: #666; margin-top: 0.15rem; }
.winner { display: inline-block; background: #1f7a1f; color: #fff;
          font-size: 0.7rem; padding: 0.05rem 0.35rem; border-radius: 3px;
          margin-bottom: 0.2rem; }
.cross-date-badge { background: #b25a00; color: #fff; padding: 0.1rem 0.5rem;
                    border-radius: 3px; font-weight: bold; font-size: 0.75rem; }
.src-badge { display: inline-block; background: #444; color: #fff;
             font-size: 0.7rem; padding: 0.05rem 0.35rem; border-radius: 3px;
             margin-bottom: 0.2rem; margin-left: 0.3rem;
             font-family: ui-monospace, Consolas, monospace; }
table.stats { border-collapse: collapse; background: #fff; margin-bottom: 1rem;
              min-width: 360px; }
table.stats th, table.stats td { padding: 0.3rem 0.7rem; border-bottom: 1px solid #eee;
                                 font-size: 0.85rem; text-align: left; }
table.stats th { background: #efefef; }
table.stats td.num { text-align: right; font-variant-numeric: tabular-nums; }
table.stats tr.total { font-weight: bold; background: #fafafa; }
h2 { font-size: 1.05rem; margin-top: 1.2rem; margin-bottom: 0.5rem; }
</style>
</head><body>
"""


def _year_from_relpath(relpath: str) -> str:
    """Extract a year bucket from a relative path.

    Folder hierarchy wins when available — preserves the master library's
    ``BUNDLED_EARLY_FOLDER`` convention verbatim ("2000 - 2010" stays as-is).
    For flat layouts (pilot dest, or any file directly under the root) the
    year is derived from the canonical ``YYYY-`` prefix on the filename
    itself; years in the bundled-early range collapse to
    ``BUNDLED_EARLY_FOLDER`` so flat and nested layouts agree.
    """
    parts = relpath.replace("\\", "/").split("/")
    if len(parts) >= 2:
        first = parts[0]
        if first[:4].isdigit():
            return first
    basename = parts[-1]
    year_prefix = basename[:4]
    if year_prefix.isdigit():
        year = int(year_prefix)
        if year in _BUNDLED_EARLY_YEARS:
            return BUNDLED_EARLY_FOLDER
        return year_prefix
    return "(no year)"


def render_singletons_html_report(
    singletons: Iterable[FileFingerprint],
    library_root: str,
    source_labels: dict[str, str] | None = None,
    thumbnails: dict[str, str | None] | None = None,
) -> str:
    """Render an HTML report of files that weren't grouped as duplicates.

    Useful for spotting files that exist in only one source — after a combine
    of master + takeout, a singleton is either a genuine one-of-a-kind photo
    OR a file whose perceptual signature was too far from any sibling to
    cluster at the chosen threshold.

    Grouped by year folder, thumbnails inlined just like the dupes report.
    ``source_labels`` is the provenance map from ``SourceManifest.all_entries``
    — when supplied, each card carries an ``src: <label>`` badge so a
    singleton's source library is visible at a glance.
    """
    by_year: dict[str, list[FileFingerprint]] = {}
    for fingerprint in singletons:
        relpath = os.path.relpath(fingerprint.path, library_root)
        year = _year_from_relpath(relpath)
        by_year.setdefault(year, []).append(fingerprint)

    parts = [_HTML_HEAD]
    parts.append(
        f'<h1>Singletons — files not in any duplicate group — '
        f'{html.escape(os.path.basename(library_root) or library_root)}</h1>'
    )
    total = sum(len(items) for items in by_year.values())
    parts.append(
        f'<div class="summary">'
        f'  {total} singleton files across {len(by_year)} year buckets. '
        f'  These have no detected duplicate at the current pHash threshold — '
        f'  they may be one-of-a-kind originals OR cases where the dedup missed.'
        f'</div>'
    )
    for year in sorted(by_year.keys()):
        items = sorted(by_year[year], key=lambda fp: fp.path)
        cards = "\n".join(
            _render_card(
                fingerprint, position=1,
                library_root=library_root,
                source_labels=source_labels,
                thumbnails=thumbnails,
            )
            for fingerprint in items
        )
        parts.append(
            f'<div class="group">'
            f'  <div class="group-header" style="border-left-color: #555">'
            f'    <span class="tier-badge" style="background: #555">{html.escape(year)}</span>'
            f'    <span class="count">{len(items)} singletons</span>'
            f'  </div>'
            f'  <div class="cards">{cards}</div>'
            f'</div>'
        )
    parts.append("</body></html>")
    return "\n".join(parts)


def _bucket_year(fingerprint: FileFingerprint, library_root: str) -> str:
    return _year_from_relpath(os.path.relpath(fingerprint.path, library_root))


def _extension_of(fingerprint: FileFingerprint) -> str:
    ext = os.path.splitext(fingerprint.path)[1].lstrip(".").lower()
    return ext or "(none)"


def _render_stats_table(
    headers: tuple[str, ...],
    rows: list[tuple],
    total_row: tuple | None = None,
) -> str:
    """Render a stats table. ``rows`` / ``total_row`` are tuples whose length
    matches ``headers``. Cells after the first are treated as numeric and
    right-aligned.
    """
    head_cells = "".join(f"<th>{html.escape(h)}</th>" for h in headers)
    body_cells = []
    for row in rows:
        cells = [f"<td>{html.escape(str(row[0]))}</td>"]
        cells += [f'<td class="num">{html.escape(str(value))}</td>' for value in row[1:]]
        body_cells.append("<tr>" + "".join(cells) + "</tr>")
    total_html = ""
    if total_row is not None:
        cells = [f"<td>{html.escape(str(total_row[0]))}</td>"]
        cells += [f'<td class="num">{html.escape(str(value))}</td>' for value in total_row[1:]]
        total_html = '<tr class="total">' + "".join(cells) + "</tr>"
    return (
        '<table class="stats">'
        f'<thead><tr>{head_cells}</tr></thead>'
        f'<tbody>{"".join(body_cells)}{total_html}</tbody>'
        '</table>'
    )


def render_stats_html_report(
    fingerprints: Iterable[FileFingerprint],
    groups: Iterable[DuplicateGroup],
    library_root: str,
    source_labels: dict[str, str] | None = None,
) -> str:
    """Library overview: counts and sizes by year / extension / media kind,
    plus a duplicate-group rollup showing how many bytes the manual review
    could plausibly reclaim (sum of loser sizes across all groups).

    When ``source_labels`` is provided (typically from the combine manifest),
    an additional "By source" table breaks files down by their source library.
    """
    fingerprints = list(fingerprints)
    groups = list(groups)

    total_files = len(fingerprints)
    total_bytes = sum(fp.size for fp in fingerprints)

    by_year: dict[str, list[FileFingerprint]] = {}
    by_extension: dict[str, list[FileFingerprint]] = {}
    by_media_kind: dict[str, list[FileFingerprint]] = {}
    by_source: dict[str, list[FileFingerprint]] = {}
    for fingerprint in fingerprints:
        by_year.setdefault(_bucket_year(fingerprint, library_root), []).append(fingerprint)
        by_extension.setdefault(_extension_of(fingerprint), []).append(fingerprint)
        by_media_kind.setdefault(fingerprint.media_kind, []).append(fingerprint)
        if source_labels:
            label = source_labels.get(os.path.normpath(fingerprint.path), "(unknown)")
            by_source.setdefault(label, []).append(fingerprint)

    groups_by_tier: dict[int, list[DuplicateGroup]] = {1: [], 2: [], 3: []}
    files_in_groups = 0
    loser_bytes = 0
    for group in groups:
        groups_by_tier.setdefault(group.tier, []).append(group)
        files_in_groups += len(group.fingerprints)
        ranked = group.ranked()
        loser_bytes += sum(fp.size for fp in ranked[1:])

    parts = [_HTML_HEAD]
    parts.append(
        f'<h1>Library statistics — '
        f'{html.escape(os.path.basename(library_root) or library_root)}</h1>'
    )
    parts.append(
        f'<div class="summary">'
        f'  <b>{total_files}</b> files · <b>{_format_size(total_bytes)}</b> · '
        f'  {len(by_year)} year buckets · '
        f'  {len(by_extension)} extensions · '
        f'  {len(groups)} duplicate groups'
        f'</div>'
    )

    parts.append("<h2>By year</h2>")
    year_rows = [
        (year, len(items), _format_size(sum(fp.size for fp in items)))
        for year, items in sorted(by_year.items())
    ]
    parts.append(_render_stats_table(
        ("Year", "Files", "Size"),
        year_rows,
        ("Total", total_files, _format_size(total_bytes)),
    ))

    parts.append("<h2>By extension</h2>")
    extension_rows = []
    for ext, items in sorted(by_extension.items(), key=lambda kv: -sum(fp.size for fp in kv[1])):
        bytes_for_ext = sum(fp.size for fp in items)
        pct = (bytes_for_ext / total_bytes * 100) if total_bytes else 0
        extension_rows.append((
            ext, len(items), _format_size(bytes_for_ext), f"{pct:.1f}%",
        ))
    parts.append(_render_stats_table(
        ("Extension", "Files", "Size", "% bytes"),
        extension_rows,
        ("Total", total_files, _format_size(total_bytes), "100.0%"),
    ))

    parts.append("<h2>By media kind</h2>")
    media_rows = [
        (kind, len(items), _format_size(sum(fp.size for fp in items)))
        for kind, items in sorted(by_media_kind.items())
    ]
    parts.append(_render_stats_table(
        ("Media kind", "Files", "Size"),
        media_rows,
    ))

    if by_source:
        parts.append("<h2>By source library</h2>")
        source_rows = []
        for label, items in sorted(by_source.items(), key=lambda kv: -len(kv[1])):
            bytes_for_source = sum(fp.size for fp in items)
            pct = (len(items) / total_files * 100) if total_files else 0
            source_rows.append((
                label, len(items), _format_size(bytes_for_source), f"{pct:.1f}%",
            ))
        parts.append(_render_stats_table(
            ("Source", "Files", "Size", "% files"),
            source_rows,
            ("Total", total_files, _format_size(total_bytes), "100.0%"),
        ))

    parts.append("<h2>Duplicates</h2>")
    tier_rows = []
    for tier in (1, 2, 3):
        tier_groups = groups_by_tier.get(tier, [])
        label, blurb, _color = TIER_LABELS[tier]
        files_at_tier = sum(len(g.fingerprints) for g in tier_groups)
        tier_rows.append((f"{label} — {blurb}", len(tier_groups), files_at_tier))
    parts.append(_render_stats_table(
        ("Tier", "Groups", "Files"),
        tier_rows,
        ("Total", len(groups), files_in_groups),
    ))
    parts.append(
        f'<div class="summary">'
        f'  Manual review of the {len(groups)} groups could reclaim up to '
        f'  <b>{_format_size(loser_bytes)}</b> '
        f'  (sum of sizes of all non-winners). Singletons: <b>{total_files - files_in_groups}</b>.'
        f'</div>'
    )

    parts.append("</body></html>")
    return "\n".join(parts)


def render_html_report(
    groups: Iterable[DuplicateGroup],
    library_root: str,
    source_labels: dict[str, str] | None = None,
    thumbnails: dict[str, str | None] | None = None,
) -> str:
    """Return a complete HTML document string for the given duplicate groups.

    ``source_labels`` (from ``SourceManifest.all_entries``) is optional —
    when present, each card carries a ``src: <label>`` badge showing the
    library the file came from.

    ``thumbnails`` is an optional ``{path: data_uri}`` cache from
    ``precompute_thumbnails``. When given, no synchronous thumbnail
    generation happens here — useful for big libraries where the
    parallel precompute is much faster than the sequential fallback.
    """
    materialized = list(groups)
    groups_by_tier = {1: [], 2: [], 3: []}
    for group in materialized:
        groups_by_tier.setdefault(group.tier, []).append(group)
    total_files = sum(len(group.fingerprints) for group in materialized)
    parts = [_HTML_HEAD]
    parts.append(
        f'<h1>Duplicate review — '
        f'{html.escape(os.path.basename(library_root) or library_root)}</h1>'
    )
    parts.append(
        f'<div class="summary">'
        f'  {len(materialized)} groups, {total_files} files. '
        f'  Tier 1: {len(groups_by_tier[1])}; '
        f'  Tier 2: {len(groups_by_tier[2])}; '
        f'  Tier 3: {len(groups_by_tier[3])}.'
        f'</div>'
    )
    sorted_groups = sorted(materialized, key=lambda g: (g.tier, -len(g.fingerprints)))
    for group in sorted_groups:
        parts.append(_render_group(
            group, library_root,
            source_labels=source_labels, thumbnails=thumbnails,
        ))
    parts.append("</body></html>")
    return "\n".join(parts)
